spring:
  datasource:
#    url: jdbc:h2:mem:usuarios
    url: jdbc:h2:./db/usuarios
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    properties.hibernate-dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate.ddl-auto: update